sudo: required
language: node
services:
  - docker

before_install:
  - docker build -t myates/ww-b-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true myates/ww-b-dev
  - docker build -t myates/ww-backend .
  - echo docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - docker push myates/ww-backend:latest
