version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports: 
    - "5000:5000"
    expose:
     - 5000
  postgres:
    image: postgres:latest
    # build: ./postgres
    container_name: "pg-docker"
    restart: always
    # env_file: 
    #   - ./config/dev.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: