version: "3"
services:
  wallwander-api:
    container_name: wallwander-api
    build: ./
    command: npm start
    ports:
      - "4000:4000"
    restart: always
  postgres:
    image: postgres:latest
    container_name: "pg-docker"
    restart: always
    # env_file:
    #   - ./config/dev.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
